List<String> States = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal'
];

Map<String,List<String>> Districts = {
  'Andhra Pradesh': [
    'Anantapur',
    'Chittoor',
    'East Godavari',
    'Alluri Sitarama Raju',
    'Anakapalli',
    'Annamaya',
    'Bapatla',
    'Eluru',
    'Guntur',
    'Kadapa',
    'Kakinada',
    'Konaseema',
    'Krishna',
    'Kurnool',
    'Manyam',
    'N T Rama Rao',
    'Nandyal',
    'Nellore',
    'Palnadu',
    'Prakasam',
    'Sri Balaji',
    'Sri Satya Sai',
    'Srikakulam',
    'Visakhapatnam',
    'Vizianagaram',
    'West Godavari'
  ],
  'Arunachal Pradesh': [
    'Anjaw',
    'Central Siang',
    'Changlang',
    'Dibang Valley',
    'East Kameng',
    'East Siang',
    'Kamle',
    'Kra Daadi',
    'Kurung Kumey',
    'Lepa Rada',
    'Lohit',
    'Longding',
    'Lower Dibang Valley',
    'Lower Siang',
    'Lower Subansiri',
    'Namsai',
    'Pakke Kessang',
    'Papum Pare',
    'Shi Yomi',
    'Tawang',
    'Tirap',
    'Upper Siang',
    'Upper Subansiri',
    'West Kameng',
    'West Siang'
  ],
  'Assam': [
    'Bajali',
    'Baksa',
    'Barpeta',
    'Biswanath',
    'Bongaigaon',
    'Cachar',
    'Charaideo',
    'Chirang',
    'Darrang',
    'Dhemaji',
    'Dhubri',
    'Dibrugarh',
    'Dima Hasao',
    'Goalpara',
    'Golaghat',
    'Hailakandi',
    'Hojai',
    'Jorhat',
    'Kamrup',
    'Kamrup Metropolitan',
    'Karbi Anglong',
    'Karimganj',
    'Kokrajhar',
    'Lakhimpur',
    'Majuli',
    'Morigaon',
    'Nagaon',
    'Nalbari',
    'Sivasagar',
    'Sonitpur',
    'South Salmara-Mankachar',
    'Tinsukia',
    'Udalguri',
    'West Karbi Anglong'
  ],
  'Bihar': [
    'Araria',
    'Arwal',
    'Aurangabad',
    'Banka',
    'Begusarai',
    'Bhagalpur',
    'Bhojpur',
    'Buxar',
    'Darbhanga',
    'East Champaran',
    'Gaya',
    'Gopalganj',
    'Jamui',
    'Jehanabad',
    'Kaimur',
    'Katihar',
    'Khagaria',
    'Kishanganj',
    'Lakhisarai',
    'Madhepura',
    'Madhubani',
    'Munger',
    'Muzaffarpur',
    'Nalanda',
    'Nawada',
    'Patna',
    'Purnia',
    'Rohtas',
    'Saharsa',
    'Samastipur',
    'Saran',
    'Sheikhpura',
    'Sheohar',
    'Sitamarhi',
    'Siwan',
    'Supaul',
    'Vaishali',
    'West Champaran'
  ],
  'Chhattisgarh': [
    'Balod',
    'Baloda Bazar',
    'Balrampur',
    'Bastar',
    'Bemetara',
    'Bijapur',
    'Bilaspur',
    'Dantewada',
    'Dhamtari',
    'Durg',
    'Gariaband',
    'Gaurela Pendra Marwahi',
    'Janjgir Champa',
    'Jashpur',
    'Kabirdham',
    'Kanker',
    'Kondagaon',
    'Korba',
    'Koriya',
    'Mahasamund',
    'Manendragarh',
    'Mohla Manpur',
    'Mungeli',
    'Narayanpur',
    'Raigarh',
    'Raipur',
    'Rajnandgaon',
    'Sakti',
    'Sarangarh Bilaigarh',
    'Sukma',
    'Surajpur',
    'Surguja'
  ],
  'Goa': ['North Goa', 'South Goa'],
  'Gujarat': [
    'Ahmedabad',
    'Amreli',
    'Anand',
    'Aravalli',
    'Banaskantha',
    'Bharuch',
    'Bhavnagar',
    'Botad',
    'Chhota Udaipur',
    'Dahod',
    'Dang',
    'Devbhoomi Dwarka',
    'Gandhinagar',
    'Gir Somnath',
    'Jamnagar',
    'Junagadh',
    'Kheda',
    'Kutch',
    'Mahisagar',
    'Mehsana',
    'Morbi',
    'Narmada',
    'Navsari',
    'Panchmahal',
    'Patan',
    'Porbandar',
    'Rajkot',
    'Sabarkantha',
    'Surat',
    'Surendranagar',
    'Tapi',
    'Vadodara',
    'Valsad'
  ],
  'Haryana': [
    'Ambala',
    'Bhiwani',
    'Charkhi Dadri',
    'Faridabad',
    'Fatehabad',
    'Gurugram',
    'Hisar',
    'Jhajjar',
    'Jind',
    'Kaithal',
    'Karnal',
    'Kurukshetra',
    'Mahendragarh',
    'Mewat',
    'Palwal',
    'Panchkula',
    'Panipat',
    'Rewari',
    'Rohtak',
    'Sirsa',
    'Sonipat',
    'Yamunanagar'
  ],
  'Himachal Pradesh': [
    'Bilaspur',
    'Chamba',
    'Hamirpur',
    'Kangra',
    'Kinnaur',
    'Kullu',
    'Lahaul Spiti',
    'Mandi',
    'Shimla',
    'Sirmaur',
    'Solan',
    'Una'
  ],
  'Jharkhand': [
    'Bokaro',
    'Chatra',
    'Deoghar',
    'Dhanbad',
    'Dumka',
    'East Singhbhum',
    'Garhwa',
    'Giridih',
    'Godda',
    'Gumla',
    'Hazaribagh',
    'Jamtara',
    'Khunti',
    'Koderma',
    'Latehar',
    'Lohardaga',
    'Pakur',
    'Palamu',
    'Ramgarh',
    'Ranchi',
    'Sahebganj',
    'Seraikela Kharsawan',
    'Simdega',
    'West Singhbhum'
  ],
  'Karnataka': [
    'Bagalkot',
    'Bangalore Rural',
    'Bangalore Urban',
    'Belgaum',
    'Bellary',
    'Bidar',
    'Chamarajanagar',
    'Chikkaballapur',
    'Chikkamagaluru',
    'Chitradurga',
    'Dakshina Kannada',
    'Davanagere',
    'Dharwad',
    'Gadag',
    'Gulbarga',
    'Hassan',
    'Haveri',
    'Kodagu',
    'Kolar',
    'Koppal',
    'Mandya',
    'Mysore',
    'Raichur',
    'Ramanagara',
    'Shimoga',
    'Tumkur',
    'Udupi',
    'Uttara Kannada',
    'Vijayanagara',
    'Vijayapura',
    'Yadgir'
  ],
  'Kerala': [
    'Alappuzha',
    'Ernakulam',
    'Idukki',
    'Kannur',
    'Kasaragod',
    'Kollam',
    'Kottayam',
    'Kozhikode',
    'Malappuram',
    'Palakkad',
    'Pathanamthitta',
    'Thiruvananthapuram',
    'Thrissur',
    'Wayanad'
  ],
  'Madhya Pradesh': [
    'Agar Malwa',
    'Alirajpur',
    'Anuppur',
    'Ashoknagar',
    'Balaghat',
    'Barwani',
    'Betul',
    'Bhind',
    'Bhopal',
    'Burhanpur',
    'Chachaura',
    'Chhatarpur',
    'Chhindwara',
    'Damoh',
    'Datia',
    'Dewas',
    'Dhar',
    'Dindori',
    'Guna',
    'Gwalior',
    'Harda',
    'Hoshangabad',
    'Indore',
    'Jabalpur',
    'Jhabua',
    'Katni',
    'Khandwa',
    'Khargone',
    'Maihar',
    'Mandla',
    'Mandsaur',
    'Morena',
    'Narsinghpur',
    'Nagda',
    'Neemuch',
    'Niwari',
    'Panna',
    'Raisen',
    'Rajgarh',
    'Ratlam',
    'Rewa',
    'Sagar',
    'Satna',
    'Sehore',
    'Seoni',
    'Shahdol',
    'Shajapur',
    'Sheopur',
    'Shivpuri',
    'Sidhi',
    'Singrauli',
    'Tikamgarh',
    'Ujjain',
    'Umaria',
    'Vidisha'
  ],
  'Maharashtra': [
    'Ahmednagar',
    'Akola',
    'Amravati',
    'Aurangabad',
    'Beed',
    'Bhandara',
    'Buldhana',
    'Chandrapur',
    'Dhule',
    'Gadchiroli',
    'Gondia',
    'Hingoli',
    'Jalgaon',
    'Jalna',
    'Kolhapur',
    'Latur',
    'Mumbai City',
    'Mumbai Suburban',
    'Nagpur',
    'Nanded',
    'Nandurbar',
    'Nashik',
    'Osmanabad',
    'Palghar',
    'Parbhani',
    'Pune',
    'Raigad',
    'Ratnagiri',
    'Sangli',
    'Satara',
    'Sindhudurg',
    'Solapur',
    'Thane',
    'Wardha',
    'Washim',
    'Yavatmal'
  ],
  'Manipur': [
    'Bishnupur',
    'Chandel',
    'Churachandpur',
    'Imphal East',
    'Imphal West',
    'Jiribam',
    'Kakching',
    'Kamjong',
    'Kangpokpi',
    'Noney',
    'Pherzawl',
    'Senapati',
    'Tamenglong',
    'Tengnoupal',
    'Thoubal',
    'Ukhrul'
  ],
  'Meghalaya': [
    'East Garo Hills',
    'East Jaintia Hills',
    'East Khasi Hills',
    'Mairang',
    'North Garo Hills',
    'Ri Bhoi',
    'South Garo Hills',
    'South West Garo Hills',
    'South West Khasi Hills',
    'West Garo Hills',
    'West Jaintia Hills',
    'West Khasi Hills'
  ],
  'Mizoram': [
    'Aizawl',
    'Champhai',
    'Hnahthial',
    'Kolasib',
    'Khawzawl',
    'Lawngtlai',
    'Lunglei',
    'Mamit',
    'Saiha',
    'Serchhip',
    'Saitual'
  ],
  'Nagaland': [
    'Chumukedima',
    'Dimapur',
    'Kiphire',
    'Kohima',
    'Longleng',
    'Mokokchung',
    'Mon',
    'Noklak',
    'Niuland',
    'Peren',
    'Phek',
    'Tseminyu',
    'Tuensang',
    'Wokha',
    'Zunheboto'
  ],
  'Odisha': [
    'Angul',
    'Balangir',
    'Balasore',
    'Bargarh',
    'Bhadrak',
    'Boudh',
    'Cuttack',
    'Debagarh',
    'Dhenkanal',
    'Gajapati',
    'Ganjam',
    'Jagatsinghpur',
    'Jajpur',
    'Jharsuguda',
    'Kalahandi',
    'Kandhamal',
    'Kendrapara',
    'Kendujhar',
    'Khordha',
    'Koraput',
    'Malkangiri',
    'Mayurbhanj',
    'Nabarangpur',
    'Nayagarh',
    'Nuapada',
    'Puri',
    'Rayagada',
    'Sambalpur',
    'Subarnapur',
    'Sundergarh'
  ],
  'Punjab': [
    'Amritsar',
    'Barnala',
    'Bathinda',
    'Faridkot',
    'Fatehgarh Sahib',
    'Fazilka',
    'Firozpur',
    'Gurdaspur',
    'Hoshiarpur',
    'Jalandhar',
    'Kapurthala',
    'Ludhiana',
    'Malerkotla',
    'Mansa',
    'Moga',
    'Mohali',
    'Muktsar',
    'Pathankot',
    'Patiala',
    'Rupnagar',
    'Sangrur',
    'Shaheed Bhagat Singh Nagar',
    'Tarn Taran'
  ],
  'Rajasthan': [
    'Ajmer',
    'Alwar',
    'Banswara',
    'Baran',
    'Barmer',
    'Bharatpur',
    'Bhilwara',
    'Bikaner',
    'Bundi',
    'Chittorgarh',
    'Churu',
    'Dausa',
    'Dholpur',
    'Dungarpur',
    'Hanumangarh',
    'Jaipur',
    'Jaisalmer',
    'Jalore',
    'Jhalawar',
    'Jhunjhunu',
    'Jodhpur',
    'Karauli',
    'Kota',
    'Nagaur',
    'Pali',
    'Pratapgarh',
    'Rajsamand',
    'Sawai Madhopur',
    'Sikar',
    'Sirohi',
    'Sri Ganganagar',
    'Tonk',
    'Udaipur'
  ],
  'Sikkim': [
    'East Sikkim',
    'North Sikkim',
    'Pakyong',
    'Soreng',
    'South Sikkim',
    'West Sikkim'
  ],
  'Tamil Nadu': [
    'Ariyalur',
    'Chengalpattu',
    'Chennai',
    'Coimbatore',
    'Cuddalore',
    'Dharmapuri',
    'Dindigul',
    'Erode',
    'Kallakurichi',
    'Kancheepuram',
    'Kanniyakumari',
    'Karur',
    'Krishnagiri',
    'Madurai',
    'Mayiladuthurai',
    'Nagapattinam',
    'Namakkal',
    'The Nilgiris (Udagamandalam)',
    'Perambalur',
    'Pudukottai',
    'Ramanathapuram',
    'Ranipet',
    'Salem',
    'Sivagangai',
    'Tenkasi',
    'Thanjavur',
    'Theni',
    'Thoothukudi',
    'Tiruchirappalli',
    'Tirunelveli',
    'Tirupathur',
    'Tiruppur',
    'Thiruvallur',
    'Thiruvannamalai',
    'Thiruvarur',
    'Vellore',
    'Villupuram',
    'Virudhunagar'
  ],
  'Telangana': [
    'Adilabad',
    'Bhadradri Kothagudem',
    'Hyderabad',
    'Jagtial',
    'Jangaon',
    'Jayashankar',
    'Jogulamba',
    'Kamareddy',
    'Karimnagar',
    'Khammam',
    'Komaram Bheem',
    'Mahabubabad',
    'Mahbubnagar',
    'Mancherial',
    'Medak',
    'Medchal',
    'Mulugu',
    'Nagarkurnool',
    'Nalgonda',
    'Narayanpet',
    'Nirmal',
    'Nizamabad',
    'Peddapalli',
    'Rajanna Sircilla',
    'Ranga Reddy',
    'Sangareddy',
    'Siddipet',
    'Suryapet',
    'Vikarabad',
    'Wanaparthy',
    'Warangal',
    'Hanumakonda',
    'Yadadri Bhuvanagiri'
  ],
  'Tripura': [
    'Dhalai',
    'Gomati',
    'Khowai',
    'North Tripura',
    'Sepahijala',
    'South Tripura',
    'Unakoti',
    'West Tripura'
  ],
  'Uttar Pradesh': [
    'Agra',
    'Aligarh',
    'Ambedkar Nagar',
    'Amethi',
    'Amroha',
    'Auraiya',
    'Ayodhya',
    'Azamgarh',
    'Baghpat',
    'Bahraich',
    'Ballia',
    'Balrampur',
    'Banda',
    'Barabanki',
    'Bareilly',
    'Basti',
    'Bhadohi',
    'Bijnor',
    'Budaun',
    'Bulandshahr',
    'Chandauli',
    'Chitrakoot',
    'Deoria',
    'Etah',
    'Etawah',
    'Farrukhabad',
    'Fatehpur',
    'Firozabad',
    'Gautam Buddha Nagar',
    'Ghaziabad',
    'Ghazipur',
    'Gonda',
    'Gorakhpur',
    'Hamirpur',
    'Hapur',
    'Hardoi',
    'Hathras',
    'Jalaun',
    'Jaunpur',
    'Jhansi',
    'Kannauj',
    'Kanpur Dehat',
    'Kanpur Nagar',
    'Kasganj',
    'Kaushambi',
    'Kheri',
    'Kushinagar',
    'Lalitpur',
    'Lucknow',
    'Maharajganj',
    'Mahoba',
    'Mainpuri',
    'Mathura',
    'Mau',
    'Meerut',
    'Mirzapur',
    'Moradabad',
    'Muzaffarnagar',
    'Pilibhit',
    'Pratapgarh',
    'Prayagraj',
    'Raebareli',
    'Rampur',
    'Saharanpur',
    'Sambhal',
    'Sant Kabir Nagar',
    'Shahjahanpur',
    'Shamli',
    'Shravasti',
    'Siddharthnagar',
    'Sitapur',
    'Sonbhadra',
    'Sultanpur',
    'Unnao',
    'Varanasi'
  ],
  'Uttarakhand': [
    'Almora',
    'Bageshwar',
    'Chamoli',
    'Champawat',
    'Dehradun',
    'Haridwar',
    'Nainital',
    'Pauri',
    'Pithoragarh',
    'Rudraprayag',
    'Tehri',
    'Udham Singh Nagar',
    'Uttarkashi'
  ],
  'West Bengal': [
    'Alipurduar',
    'Bankura',
    'Birbhum',
    'Cooch Behar',
    'Dakshin Dinajpur',
    'Darjeeling',
    'Hooghly',
    'Howrah',
    'Jalpaiguri',
    'Jhargram',
    'Kalimpong',
    'Kolkata',
    'Malda',
    'Murshidabad',
    'Nadia',
    'North 24 Parganas',
    'Paschim Bardhaman',
    'Paschim Medinipur',
    'Purba Bardhaman',
    'Purba Medinipur',
    'Purulia',
    'South 24 Parganas',
    'Uttar Dinajpur'
  ]
};
Map<String,List<String>>Taluka = {
  'Chennai': [
    'Alandur',
    'Ambattur',
    'Aminjikarai',
    'Ayanavaram',
    'Egmore',
    'Guindy',
    'Madhavaram',
    'Madhuravoyal',
    'Mambalam',
    'Mylapore',
    'Perambur',
    'Purasavakkam',
    'Sholinganallur',
    'Thiruvottriyur',
    'Tondiarpet',
    'Velacherry'
  ],
  'Coimbatore': [
    'Aanaimalai',
    'Annur',
    'Coimbatore(North)',
    'Coimbatore(South)',
    'Kinathukadavu',
    'Madukarai',
    'Mettupalayam',
    'Perur',
    'Pollachi',
    'Sulur',
    'Valparai'
  ],
  'Cuddalore': [
    'Cuddalore',
    'Bhuvanagiri',
    'Chidambaram',
    'Kattumannarkoil',
    'Kurinjipadi',
    'Panruti',
    'Srimushnam',
    'Thittakudi',
    'Veppur',
    'Virudhachalam'
  ],
  'Dharmapuri': [
    'Dharmapuri',
    'Harur',
    'Karimangalam',
    'Nallampalli',
    'Palacode',
    'Pappireddipatti',
    'Pennagaram'
  ],
  'Dindigul': [
    'Atthur',
    'Dindigul (East)',
    'Dindigul (West)',
    'Guziliyamparai',
    'Kodaikanal',
    'Natham',
    'Nilakottai',
    'Oddanchatram',
    'Palani',
    'Vedasandur'
  ],
  'Erode': [
    'Erode',
    'Anthiyur',
    'Bhavani',
    'Gobichettipalayam',
    'Kodumudi',
    'Modakurichi',
    'Nambiyur',
    'Perundurai',
    'Sathiyamangalam',
    'Thalavadi'
  ],
  'Kancheepuram': [
    'Kancheepuram',
    'Kundrathur',
    'Sriperumbudur',
    'Uthiramerur',
    'Walajabad'
  ],
  'Kanniyakumari': [
    'Agasteeswaram',
    'Kalkulam',
    'Killiyur',
    'Thiruvatar',
    'Thovalai',
    'Vilavankodu'
  ],
  'Karur': [
    'Karur',
    'Aravakurichi',
    'Kadavur',
    'Krishnarayapuram',
    'Kulithalai',
    'Manmangalam',
    'Pugalur'
  ],
  'Madurai': [
    'Kallikudi',
    'Madurai (East)',
    'Madurai (North)',
    'Madurai (South)',
    'Madurai (West)',
    'Melur',
    'Peraiyur',
    'Thirumangalam',
    'Thiruparankundram',
    'Usilampatti',
    'Vadipatti'
  ],
  'Nagapattinam': ['Nagapattinam', 'Kilvelur', 'Thirukkuvalai', 'Vedaranyam'],
  'Namakkal': [
    'Namakkal',
    'Kholli Hills',
    'Kumarapalayam',
    'Mohanoor',
    'Paramathi Velur',
    'Rasipuram',
    'Senthamangalam',
    'Tiruchengode'
  ],
  'The Nilgiris (Udagamandalam)': [
    'Udagamandalam',
    'Coonoor',
    'Gudalur',
    'Kothagiri',
    'Kundah',
    'Pandalur'
  ],
  'Perambalur': ['Perambalur', 'Alathur', 'Kunnam', 'Veppanthattai'],
  'Pudukottai': [
    'Pudukottai',
    'Alangudi',
    'Aranthangi',
    'Avudiyarkoil',
    'Gandarvakottai',
    'Iluppur',
    'Karambakudi',
    'Kulathur',
    'Manamelkudi',
    'Ponnamaravathi',
    'Thirumayam',
    'Viralimalai'
  ],
  'Ramanathapuram': [
    'Ramanathapuram',
    'Kadaladi',
    'Kamuthi',
    'Kezhakarai',
    'Mudukulathur',
    'Paramakudi',
    'Rajasingamangalam',
    'Rameswaram',
    'Tiruvadanai'
  ],
  'Salem': [
    'Salem',
    'Attur',
    'Edapadi',
    'Gangavalli',
    'Kadaiyampatti',
    'Mettur',
    'Omalur',
    'Pethanayakanpalayam',
    'Salem South',
    'Salem West',
    'Sankari',
    'Vazhapadi',
    'Yercaud'
  ],
  'Sivagangai': [
    'Sivagangai',
    'Devakottai',
    'Ilayankudi',
    'Kalaiyarkovil',
    'Karaikudi',
    'Manamadurai',
    'Singampunari',
    'Thirupuvanam',
    'Tirupathur'
  ],
  'Thanjavur': [
    'Thanjavur',
    'Boothalur',
    'Kumbakonam',
    'Orathanadu',
    'Papanasam',
    'Pattukottai',
    'Peravurani',
    'Thiruvaiyaru',
    'Thiruvidaimaruthur'
  ],
  'Theni': [
    'Theni',
    'Aandipatti',
    'Bodinayakanur',
    'Periyakulam',
    'Uthamapalayam'
  ],
  'Thiruvallur': [
    'Thiruvallur',
    'Avadi',
    'Gummidipoondi',
    'Pallipattu',
    'Ponneri',
    'Poonamallee',
    'R.K. Pet',
    'Tiruthani',
    'Uthukottai'
  ],
  'Thiruvannamalai': [
    'Thiruvannamalai',
    'Arni',
    'Chengam',
    'Chetpet',
    'Cheyyar',
    'Jamunamarathur',
    'Kalasapakkam',
    'Kilpennathur',
    'Polur',
    'Thandramet',
    'Vandavasi',
    'Vembakkam'
  ],
  'Thiruvarur': [
    'Thiruvarur',
    'Kodavasal',
    'Koothanallur',
    'Mannargudi',
    'Nannilam',
    'Needamangalam',
    'Thiruthuraipoondi',
    'Valangaiman'
  ],
  'Thoothukudi': [
    'Thoothukudi',
    'Eral',
    'Ettayapuram',
    'Kayathar',
    'Kovilpatti',
    'Ottapidaram',
    'Sattankulam',
    'Srivaikundam',
    'Tiruchendur',
    'Vilathikulam'
  ],
  'Tiruchirappalli': [
    'Lalgudi',
    'Manachanallur',
    'Manapparai',
    'Marungapuri',
    'Musiri',
    'Srirangam',
    'Thottiam',
    'Thuraiyur',
    'Tiruchirapalli (West)',
    'Tiruchirappalli (East)',
    'Tiruverumbur'
  ],
  'Tirunelveli': [
    'Tirunelveli',
    'Ambasamudram',
    'Cheranmahadevi',
    'Manur',
    'Nanguneri',
    'Palayamkottai',
    'Radhapuram',
    'Thisayanvilai'
  ],
  'Vellore': [
    'Vellore',
    'Aanikattu',
    'Gudiyatham',
    'K V Kuppam',
    'Katpadi',
    'Pernambut'
  ],
  'Villupuram': [
    'Villupuram',
    'Gingee',
    'Kandachipuram',
    'Marakanam',
    'Melmalaiyanur',
    'Thiruvennainallur',
    'Tindivanam',
    'Vanur',
    'Vikravandi'
  ],
  'Virudhunagar': [
    'Virudhunagar',
    'Aruppukottai',
    'Kariyapatti',
    'Rajapalayam',
    'Sathur',
    'Sivakasi',
    'Srivilliputhur',
    'Tiruchuli',
    'Vembakottai',
    'Watrap'
  ],
  'Ariyalur': ['Ariyalur', 'Andimadam', 'Sendurai', 'Udaiyarpalayam'],
  'Krishnagiri': [
    'Krishnagiri',
    'Anjetty',
    'Bargur',
    'Hosur',
    'Pochampalli',
    'Sulagiri',
    'Thenkanikottai',
    'Uthangarai'
  ],
  'Tiruppur': [
    'Avinashi',
    'Dharapuram',
    'Kangeyam',
    'Madathukkulam',
    'Oothukuli',
    'Palladam',
    'Tiruppur (North)',
    'Tiruppur (South)'
  ],
  'Chengalpattu': [
    'Chengalpattu',
    'Cheyyur',
    'Maduranthakam',
    'Pallavaram',
    'Tambaram',
    'Thirukalukundram',
    'Tiruporur',
    'Vandalur'
  ],
  'Kallakurichi': [
    'Kallakurichi',
    'Chinnaselam',
    'Kalvarayan Hills',
    'Sankarapuram',
    'Tirukoilur',
    'Ulundurpet'
  ],
  'Ranipet': [
    'Arakkonam',
    'Arcot',
    'Kalavai',
    'Nemili',
    'Sholingur',
    'Walajah'
  ],
  'Tenkasi': [
    'Tenkasi',
    'Alangulam',
    'Kadayanallur',
    'Sankarankovil',
    'Shenkottai',
    'Sivagiri',
    'Thiruvengadam',
    'Veerakeralampudur'
  ],
  'Tirupathur': ['Tirupathur', 'Ambur', 'Natrampalli', 'Vaniyambadi'],
  'Mayiladuthurai': ['Mayiladuthurai', 'Kuthalam', 'Sirkali', 'Tharangambadi']
};
